-- ======================= --
--       GOSSIP_TEXTS      --
-- ======================= --
--    ScriptDev2 2360     --
-- ======================= --

ALTER TABLE `gossip_texts` CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;

UPDATE `gossip_texts` SET `content_loc7`='[PH] Texto de SD2 no encontrado' WHERE `entry`='-3000000';
UPDATE `gossip_texts` SET `content_loc7`='Taruk me manda a cobrar lo que debes.' WHERE `entry`='-3000101';
UPDATE `gossip_texts` SET `content_loc7`='¡Aquí está el dinero!' WHERE `entry`='-3000102';
UPDATE `gossip_texts` SET `content_loc7`='Ya estoy list$go:a; para viajar a tu aldea.' WHERE `entry`='-3000103';
UPDATE `gossip_texts` SET `content_loc7`='<Comprueba si hay pulso...>' WHERE `entry`='-3000104';
UPDATE `gossip_texts` SET `content_loc7`='Ezequiel dijo que podrías tener cierto libro...' WHERE `entry`='-3000105';
UPDATE `gossip_texts` SET `content_loc7`='Muéstrame dónde puedo volar.' WHERE `entry`='-3000106';
UPDATE `gossip_texts` SET `content_loc7`='[PH] Conseguir bombas de precisión' WHERE `entry`='-3000107';
UPDATE `gossip_texts` SET `content_loc7`='[PH] Inicio misión de bombardeo' WHERE `entry`='-3000108';
UPDATE `gossip_texts` SET `content_loc7`='Cambiar 100 Puntos de Arenas por 2000 Puntos de Honor' WHERE `entry`='-3000770';
UPDATE `gossip_texts` SET `content_loc7`='Cambiar 1000 Puntos de Arenas por 20000 Puntos de Honor' WHERE `entry`='-3000771';
UPDATE `gossip_texts` SET `content_loc7`='Cambiar 1000 Puntos de Honor por 50 Puntos de Arenas' WHERE `entry`='-3000772';
UPDATE `gossip_texts` SET `content_loc7`='Cambiar 10000 Puntos de Honor por 500 Puntos de Arenas' WHERE `entry`='-3000773';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, abrir la puerta del patio.' WHERE `entry`='-3033000';
UPDATE `gossip_texts` SET `content_loc7`='¡Que empiece el evento!' WHERE `entry`='-3043000';
UPDATE `gossip_texts` SET `content_loc7`='Estoy list$go:a; para empezar.' WHERE `entry`='-3090000';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame cómo convertirme en $gun Maestro:una Maestra; de pociones, Lauranna' WHERE `entry`='-3100000';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar la Maestría en Pociones' WHERE `entry`='-3100001';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame cómo convertirme en $gun Maestro:una Maestra; de Trasmutaciones, Zarevhi' WHERE `entry`='-3100002';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar la Maestría en Transmutaciones' WHERE `entry`='-3100003';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame cómo convertirme en $gun Maestro:una Maestra; en elixires, Lorokeem' WHERE `entry`='-3100004';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar la Maestría en Elixires' WHERE `entry`='-3100005';
UPDATE `gossip_texts` SET `content_loc7`='¿De verdad quieres olvidar tu especialidad en alquimia y perder todas las recetas asociadas?$bCoste:' WHERE `entry`='-3100006';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame a convertirme en un $GForjador:Forjadora; de Armas' WHERE `entry`='-3100007';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar oficio de $GForjador:Forjadora; de Armas' WHERE `entry`='-3100008';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame a convertirme en un $GForjador:Forjadora; de Armaduras' WHERE `entry`='-3100009';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar oficio de $GForjador:Forjadora; de Armaduras' WHERE `entry`='-3100010';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar mi especialidad de herrería' WHERE `entry`='-3100011';
UPDATE `gossip_texts` SET `content_loc7`='¿De verdad quieres olvidar tu especialidad en herrería y perder todas las recetas asociadas?$bCoste:' WHERE `entry`='-3100012';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame a convertirme en un $GForjador:Forjadora; de Martillos, Lilith' WHERE `entry`='-3100013';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar el Forjado de Martillos' WHERE `entry`='-3100014';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame a convertirme en un $GForjador:Forjadora; de Hachas, Kilram' WHERE `entry`='-3100015';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar el Forjado de Hachas' WHERE `entry`='-3100016';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame a convertirme en un $gArmero:Armera;, Seril' WHERE `entry`='-3100017';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar Armería' WHERE `entry`='-3100018';
UPDATE `gossip_texts` SET `content_loc7`='¿De verdad quieres olvidar tu especialidad de forjador de armas y perder todas las recetas asociadas?$bCoste:' WHERE `entry`='-3100019';
UPDATE `gossip_texts` SET `content_loc7`='Estoy completamente $gseguro:segura; que quiero aprender Peletería Dragontina' WHERE `entry`='-3100020';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar Peletería Dragontina' WHERE `entry`='-3100021';
UPDATE `gossip_texts` SET `content_loc7`='Estoy completamente $gseguro:segura; que quiero aprender Peletería Elemental' WHERE `entry`='-3100022';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar Peletería Elemental' WHERE `entry`='-3100023';
UPDATE `gossip_texts` SET `content_loc7`='Estoy completamente $gseguro:segura; que quiero aprender Peletería Tribal' WHERE `entry`='-3100024';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar Peletería Tribal' WHERE `entry`='-3100025';
UPDATE `gossip_texts` SET `content_loc7`='¿De verdad quieres olvidar tu especialidad en peletería y perder todas las recetas asociadas?$bCoste:' WHERE `entry`='-3100026';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame a convertirme en $gun:una; Sastre de paños de hechizos' WHERE `entry`='-3100027';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar Satrería en Fuego de hechizos' WHERE `entry`='-3100028';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame a convertirme en $gun:una; Sastre de Tela lunar' WHERE `entry`='-3100029';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar Satrería en Tela lunar' WHERE `entry`='-3100030';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, enséñame a convertirme en $gun:una; Sastre de Tejidos de sombra' WHERE `entry`='-3100031';
UPDATE `gossip_texts` SET `content_loc7`='Quiero olvidar Satrería en Tejidos de sombra' WHERE `entry`='-3100032';
UPDATE `gossip_texts` SET `content_loc7`='¿De verdad quieres olvidar tu especialidad en sastrería y perder todas las recetas asociadas?$bCoste:' WHERE `entry`='-3100033';
UPDATE `gossip_texts` SET `content_loc7`='Estoy completamente $gseguro:segura; que quiero aprender Ingeniería goblin' WHERE `entry`='-3100034';
UPDATE `gossip_texts` SET `content_loc7`='Estoy completamente $gseguro:segura; que quiero aprender Ingeniería gnómica' WHERE `entry`='-3100035';
UPDATE `gossip_texts` SET `content_loc7`='¡Truco o Trato!' WHERE `entry`='-3100036';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué puedo hacer en una posada?' WHERE `entry`='-3100037';
UPDATE `gossip_texts` SET `content_loc7`='Estoy list$go:a; para ser teleportad$go:a; a Dalaran.' WHERE `entry`='-3100038';
UPDATE `gossip_texts` SET `content_loc7`='Habéis pensado bien, espíritus. Os pido que nos concedáis fuerza en el cuerpo y en el corazón.' WHERE `entry`='-3100039';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Tabardo de Caballero de sangre.' WHERE `entry`='-3100040';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Tabardo de Mano.' WHERE `entry`='-3100041';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Tabardo de Protector' WHERE `entry`='-3100042';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Tabardo trofeo verde de los Illidari' WHERE `entry`='-3100043';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Tabardo trofeo púrpura de los Illidari' WHERE `entry`='-3100044';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Tabardo de cielos estivales.' WHERE `entry`='-3100045';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Tabardo de llamas estivales.' WHERE `entry`='-3100046';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mis Colores de maestro cultural.' WHERE `entry`='-3100047';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Tabardo de Explorador.' WHERE `entry`='-3100048';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Tabardo del triunfador.' WHERE `entry`='-3100049';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Llave de El Arcatraz.' WHERE `entry`='-3100050';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Llave del Bastión de Roca Negra' WHERE `entry`='-3100051';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Llave de Scholomance.' WHERE `entry`='-3100052';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Llave de las Salas Arrasadas.' WHERE `entry`='-3100053';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Llave de Karazhan.' WHERE `entry`='-3100054';
UPDATE `gossip_texts` SET `content_loc7`='Perdí mi Llave del Bastión Violeta' WHERE `entry`='-3100055';
UPDATE `gossip_texts` SET `content_loc7`='No quiero conseguir experiencia más.' WHERE `entry`='-3100056';
UPDATE `gossip_texts` SET `content_loc7`='¿Seguro que quieres dejar de adquirir experiencia?' WHERE `entry`='-3100057';
UPDATE `gossip_texts` SET `content_loc7`='Quiero poder conseguir experiencia de nuevo.' WHERE `entry`='-3100058';
UPDATE `gossip_texts` SET `content_loc7`='¿Seguro que quieres poder ganar experiencia, de nuevo?' WHERE `entry`='-3100059';
UPDATE `gossip_texts` SET `content_loc7`='Quisiera visitar el Alto de los Rapiñadores.' WHERE `entry`='-3100060';
UPDATE `gossip_texts` SET `content_loc7`='Continúa...' WHERE `entry`='-3100061';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué puede ser peor que la muerte?' WHERE `entry`='-3100062';
UPDATE `gossip_texts` SET `content_loc7`='¿Subordinados?' WHERE `entry`='-3100063';
UPDATE `gossip_texts` SET `content_loc7`='¿Cuáles son las piedras de vínculo?' WHERE `entry`='-3100064';
UPDATE `gossip_texts` SET `content_loc7`='Cuenta conmigo, Héroe' WHERE `entry`='-3100065';
UPDATE `gossip_texts` SET `content_loc7`='Voy' WHERE `entry`='-3100066';
UPDATE `gossip_texts` SET `content_loc7`='Asuntos oficiales, John. Necesito algo de información sobre el Mariscal Windsor. Háblame de cuando lo viste por última vez.' WHERE `entry`='-3100067';
UPDATE `gossip_texts` SET `content_loc7`='Entonces, ¿qué hiciste?' WHERE `entry`='-3100068';
UPDATE `gossip_texts` SET `content_loc7`='Empieza a tener sentido, enano. No quiero saber nada de vuestro cracker, vuestro papi, o cualquier otra \"discusión\".' WHERE `entry`='-3100069';
UPDATE `gossip_texts` SET `content_loc7`='¿Ferromazo?' WHERE `entry`='-3100070';
UPDATE `gossip_texts` SET `content_loc7`='Interesante… continúa John.' WHERE `entry`='-3100071';
UPDATE `gossip_texts` SET `content_loc7`='Y así es como murió Windsor...' WHERE `entry`='-3100072';
UPDATE `gossip_texts` SET `content_loc7`='Entonces, ¿cómo murió?' WHERE `entry`='-3100073';
UPDATE `gossip_texts` SET `content_loc7`='Ok, entonces ¿dónde diablos está? ¡Espera un minuto! ¿Estás borracho?' WHERE `entry`='-3100074';
UPDATE `gossip_texts` SET `content_loc7`='¿Por qué está en el Bastión de Roca Negra?' WHERE `entry`='-3100075';
UPDATE `gossip_texts` SET `content_loc7`='¿300? ¿Así que los Enanos Hierro Negro lo mataron y lo arrastrarón a las profundidades?' WHERE `entry`='-3100076';
UPDATE `gossip_texts` SET `content_loc7`='Ahh... ferromazo' WHERE `entry`='-3100077';
UPDATE `gossip_texts` SET `content_loc7`='Gracias, John Andrajoso. Tu historia fue muy alentadora e informativa' WHERE `entry`='-3100078';
UPDATE `gossip_texts` SET `content_loc7`='Estoy $gdispuesto:dispuesta; a escuchar tu relato, Tirion.' WHERE `entry`='-3100079';
UPDATE `gossip_texts` SET `content_loc7`='Gracias, Tirion. ¿Qué hay de tu identidad?' WHERE `entry`='-3100080';
UPDATE `gossip_texts` SET `content_loc7`='Eso es terrible.' WHERE `entry`='-3100081';
UPDATE `gossip_texts` SET `content_loc7`='Lo haré, Tirion.' WHERE `entry`='-3100082';
UPDATE `gossip_texts` SET `content_loc7`='Necesito algo de su tiempo, señor.' WHERE `entry`='-3100083';
UPDATE `gossip_texts` SET `content_loc7`='Por qué... sí, desde luego. Tengo algo que mostrarle justo dentro de esta edificación, Sr. Anvilward.' WHERE `entry`='-3100084';
UPDATE `gossip_texts` SET `content_loc7`='Toma la Insignia de Caballero de Sangre' WHERE `entry`='-3100085';
UPDATE `gossip_texts` SET `content_loc7`='¿Te dio el equipo de disfraces?' WHERE `entry`='-3100086';
UPDATE `gossip_texts` SET `content_loc7`='Estoy $gdispuesto:dispuesta; a escuchar' WHERE `entry`='-3100087';
UPDATE `gossip_texts` SET `content_loc7`='Es trágico. ¿Cómo pasó esto?' WHERE `entry`='-3100088';
UPDATE `gossip_texts` SET `content_loc7`='Interesante… continúa porfavor.' WHERE `entry`='-3100089';
UPDATE `gossip_texts` SET `content_loc7`='¡Increíble! ¿Cómo se atreven?' WHERE `entry`='-3100090';
UPDATE `gossip_texts` SET `content_loc7`='¡Desde luego ayudaré!' WHERE `entry`='-3100091';
UPDATE `gossip_texts` SET `content_loc7`='Por favor abra la puerta, necesito llegar a la Garganta de Fuego' WHERE `entry`='-3100092';
UPDATE `gossip_texts` SET `content_loc7`='Pero tengo que llegar allí, ¡abre la puerta ahora!' WHERE `entry`='-3100093';
UPDATE `gossip_texts` SET `content_loc7`='Ok Así, que ¿cual es ese otra manera?' WHERE `entry`='-3100094';
UPDATE `gossip_texts` SET `content_loc7`='No importa, soy invulnerable.' WHERE `entry`='-3100095';
UPDATE `gossip_texts` SET `content_loc7`='Si…' WHERE `entry`='-3100096';
UPDATE `gossip_texts` SET `content_loc7`='Ok, trataré de recordarlo.' WHERE `entry`='-3100097';
UPDATE `gossip_texts` SET `content_loc7`='¿Una llave? ¡Ok!' WHERE `entry`='-3100098';
UPDATE `gossip_texts` SET `content_loc7`='Dime, ¿que mueve esta venganza?' WHERE `entry`='-3100099';
UPDATE `gossip_texts` SET `content_loc7`='Continúa, por favor' WHERE `entry`='-3100100';
UPDATE `gossip_texts` SET `content_loc7`='Déjame consultar con mis colegas' WHERE `entry`='-3100101';
UPDATE `gossip_texts` SET `content_loc7`='Teletransportame al Núcleo de Magma' WHERE `entry`='-3100102';
UPDATE `gossip_texts` SET `content_loc7`='Cuénteame tu historia' WHERE `entry`='-3100103';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, continúa…' WHERE `entry`='-3100104';
UPDATE `gossip_texts` SET `content_loc7`='Adios' WHERE `entry`='-3100105';
UPDATE `gossip_texts` SET `content_loc7`='¿Puedes enviarme a Theramore? Tengo un mensaje urgente del Alto Señor Bolvar para Lady Jaina.' WHERE `entry`='-3100106';
UPDATE `gossip_texts` SET `content_loc7`='Perdón por la intromisión, Lady Prestor, pero el Alto Señor Bolvar me sugirió que buscara su consejo.' WHERE `entry`='-3100107';
UPDATE `gossip_texts` SET `content_loc7`='Mis disculpas, Lady Prestor.' WHERE `entry`='-3100108';
UPDATE `gossip_texts` SET `content_loc7`='Le pido perdón, Lady Prestor. No era esa mi intención.' WHERE `entry`='-3100109';
UPDATE `gossip_texts` SET `content_loc7`='Gracias por su tiempo, Lady Prestor.' WHERE `entry`='-3100110';
UPDATE `gossip_texts` SET `content_loc7`='Gul\'dan' WHERE `entry`='-3100111';
UPDATE `gossip_texts` SET `content_loc7`='Kel\'Thuzad' WHERE `entry`='-3100112';
UPDATE `gossip_texts` SET `content_loc7`='Ner\'zhul' WHERE `entry`='-3100113';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué necesita la caldera del Campo de Piedramácula?' WHERE `entry`='-3100114';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué necesita la caldera del Llanto de Dalson?' WHERE `entry`='-3100115';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué necesita la caldera rondada de El Tormento?' WHERE `entry`='-3100116';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué necesita la caldera de la Gangrena de Gahrron?' WHERE `entry`='-3100117';
UPDATE `gossip_texts` SET `content_loc7`='Gracias, necesito un focalizador vítreo' WHERE `entry`='-3100118';
UPDATE `gossip_texts` SET `content_loc7`='Gracias, necesito un focalizador vítreo' WHERE `entry`='-3100119';
UPDATE `gossip_texts` SET `content_loc7`='Gracias, necesito un focalizador vítreo' WHERE `entry`='-3100120';
UPDATE `gossip_texts` SET `content_loc7`='Gracias, necesito un focalizador vítreo' WHERE `entry`='-3100121';
UPDATE `gossip_texts` SET `content_loc7`='Estoy list$go:a; para la ilusión, Myranda.' WHERE `entry`='-3100122';
UPDATE `gossip_texts` SET `content_loc7`='¡Necesito saber donde está la princesa, Kharan!' WHERE `entry`='-3100123';
UPDATE `gossip_texts` SET `content_loc7`='¡No todo está perdido, Kharan!' WHERE `entry`='-3100124';
UPDATE `gossip_texts` SET `content_loc7`='Gor\'shak es mi amigo, puedes creerme.' WHERE `entry`='-3100125';
UPDATE `gossip_texts` SET `content_loc7`='No es suficiente, necesitas contarme más.' WHERE `entry`='-3100126';
UPDATE `gossip_texts` SET `content_loc7`='¿Y qué pasó?' WHERE `entry`='-3100127';
UPDATE `gossip_texts` SET `content_loc7`='Continúa...' WHERE `entry`='-3100128';
UPDATE `gossip_texts` SET `content_loc7`='¿Así que sospechas que alguien del interior estaba involucrado? ¿Que fueron advertidos?' WHERE `entry`='-3100129';
UPDATE `gossip_texts` SET `content_loc7`='Sigue con tu historia por favor.' WHERE `entry`='-3100130';
UPDATE `gossip_texts` SET `content_loc7`='En efecto.' WHERE `entry`='-3100131';
UPDATE `gossip_texts` SET `content_loc7`='La puerta está abierta, Kharan. Eres un hombre libre.' WHERE `entry`='-3100132';
UPDATE `gossip_texts` SET `content_loc7`='Enséñame a que tengo acceso, Lothos' WHERE `entry`='-3100133';
UPDATE `gossip_texts` SET `content_loc7`='Conseguir Contrato de la Hermandad del Torio' WHERE `entry`='-3100134';
UPDATE `gossip_texts` SET `content_loc7`='Enséñame el arte de la fundición de hierro negro' WHERE `entry`='-3100135';
UPDATE `gossip_texts` SET `content_loc7`='Continúa...' WHERE `entry`='-3100136';
UPDATE `gossip_texts` SET `content_loc7`='Quiero pagar un tributo' WHERE `entry`='-3100137';
UPDATE `gossip_texts` SET `content_loc7`='Tu esclavitud se acabó, Doom\'rel. ¡Te desafío!' WHERE `entry`='-3100138';
UPDATE `gossip_texts` SET `content_loc7`='Qué Phat lewtz ¿tienes abuela?' WHERE `entry`='-3100139';
UPDATE `gossip_texts` SET `content_loc7`='No soy un actor.' WHERE `entry`='-3100140';
UPDATE `gossip_texts` SET `content_loc7`='No soy un actor.' WHERE `entry`='-3100141';
UPDATE `gossip_texts` SET `content_loc7`='Ok, entonces, te daré una oportunidad .' WHERE `entry`='-3100142';
UPDATE `gossip_texts` SET `content_loc7`='Nunca he estado más list$go:a;.' WHERE `entry`='-3100143';
UPDATE `gossip_texts` SET `content_loc7`='Teletransportame a la Biblioteca del Guardián' WHERE `entry`='-3100147';
UPDATE `gossip_texts` SET `content_loc7`='¿Quién eres tú?' WHERE `entry`='-3100148';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué podemos hacer para ayudarte?' WHERE `entry`='-3100149';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué te trae a la Fuente del Sol?' WHERE `entry`='-3100150';
UPDATE `gossip_texts` SET `content_loc7`='¿No estás solo aquí?' WHERE `entry`='-3100151';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué querría Kil\'jaeden de una mujer mortal?' WHERE `entry`='-3100152';
UPDATE `gossip_texts` SET `content_loc7`='¡Te desafío, caballero de la Muerte!' WHERE `entry`='-3100153';
UPDATE `gossip_texts` SET `content_loc7`='Estoy list$go:a;.' WHERE `entry`='-3100154';
UPDATE `gossip_texts` SET `content_loc7`='¿Quiénes son los Terráneos?' WHERE `entry`='-3100155';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué es la \"matriz básica subterránea\"?' WHERE `entry`='-3100156';
UPDATE `gossip_texts` SET `content_loc7`='¿Cuáles son las anomalías de las que hablas?' WHERE `entry`='-3100157';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué es una base flexible de construcción?' WHERE `entry`='-3100158';
UPDATE `gossip_texts` SET `content_loc7`='Así que...  ¿los Terráneos estaban hechos de piedra?' WHERE `entry`='-3100159';
UPDATE `gossip_texts` SET `content_loc7`='¿Algo más que debería saber sobre los Terráneos?' WHERE `entry`='-3100160';
UPDATE `gossip_texts` SET `content_loc7`='Ahora creo entender la intención de los Creadores en el diseño de los Terráneos. ¿Cuáles son las anomalías Terráneas de la que hablábamos antes?' WHERE `entry`='-3100161';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué ambientes de alto estrés pueden causar que se desestabilicen los Terráneos?' WHERE `entry`='-3100162';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué sucede cuando se desestabilizan los Terráneos?' WHERE `entry`='-3100163';
UPDATE `gossip_texts` SET `content_loc7`='¿Troggs? ¿Los troggs que mencionas son lo mismo que están en el mundo actual?' WHERE `entry`='-3100164';
UPDATE `gossip_texts` SET `content_loc7`='Has mencionado dos resultados cuando se desestabilizan los Terráneos. ¿Cuál es el segundo?' WHERE `entry`='-3100165';
UPDATE `gossip_texts` SET `content_loc7`='¡¡¡Enanos!!! ¿Me estás diciendo ahora que los enanos vinieron originalmente de los Terráneos?' WHERE `entry`='-3100166';
UPDATE `gossip_texts` SET `content_loc7`='Esos enanos son los mismos que hay hoy, ¿no? ¿Los enanos tienen algún otro vínculo con los Terráneos?' WHERE `entry`='-3100167';
UPDATE `gossip_texts` SET `content_loc7`='¿Quiénes son los Creadores?' WHERE `entry`='-3100168';
UPDATE `gossip_texts` SET `content_loc7`='Esto es mucho en lo que pensar.' WHERE `entry`='-3100169';
UPDATE `gossip_texts` SET `content_loc7`='Ahora voy a acceder a los discos.' WHERE `entry`='-3100170';
UPDATE `gossip_texts` SET `content_loc7`='Te agradezco que te preocupes, pero tenemos  intención de explorar Zul\'Aman.' WHERE `entry`='-3100171';
UPDATE `gossip_texts` SET `content_loc7`='Entrega la Piedra lunar de Furia del Sur  te dejaré marchar.' WHERE `entry`='-3100172';
UPDATE `gossip_texts` SET `content_loc7`='¿Puedes ayudarme?' WHERE `entry`='-3100173';
UPDATE `gossip_texts` SET `content_loc7`='Cuentame tu historia.' WHERE `entry`='-3100174';
UPDATE `gossip_texts` SET `content_loc7`='Por favor sigue' WHERE `entry`='-3100175';
UPDATE `gossip_texts` SET `content_loc7`='No lo entiendo' WHERE `entry`='-3100176';
UPDATE `gossip_texts` SET `content_loc7`='Por supuesto' WHERE `entry`='-3100177';
UPDATE `gossip_texts` SET `content_loc7`='Lo haremos con ó sin tu ayuda, Loramus.' WHERE `entry`='-3100178';
UPDATE `gossip_texts` SET `content_loc7`='Si' WHERE `entry`='-3100179';
UPDATE `gossip_texts` SET `content_loc7`='¡Traidor! ¡Se te llevará ante la justicia!' WHERE `entry`='-3100180';
UPDATE `gossip_texts` SET `content_loc7`='Estoy list$go:a;.' WHERE `entry`='-3100181';
UPDATE `gossip_texts` SET `content_loc7`='[PH] Inserta llave' WHERE `entry`='-3100182';
UPDATE `gossip_texts` SET `content_loc7`='<Monta los grifos al Estudio Isla de Alcaz>' WHERE `entry`='-3100183';
UPDATE `gossip_texts` SET `content_loc7`='Sé que esto es algo tonto, pero tengo un joven guarda que es algo timido y quisiera un autógrafo.' WHERE `entry`='-3100184';
UPDATE `gossip_texts` SET `content_loc7`='Por favor hazme una Antorcha Cenarion' WHERE `entry`='-3100185';
UPDATE `gossip_texts` SET `content_loc7`='Compra algo, ¿quiere\'e\'?' WHERE `entry`='-3100186';
UPDATE `gossip_texts` SET `content_loc7`='Quisiera volar a Cima del Trueno.' WHERE `entry`='-3100187';
UPDATE `gossip_texts` SET `content_loc7`='¿Sabes donde puedeo encontrar Medio colgante de Resistencia acuática?' WHERE `entry`='-3100188';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué espíritu representas?' WHERE `entry`='-3100189';
UPDATE `gossip_texts` SET `content_loc7`='Procuro entender la importancia de la fuerza del cuerpo.' WHERE `entry`='-3100190';
UPDATE `gossip_texts` SET `content_loc7`='Procuro entender la importancia de la fuerza del corazón.' WHERE `entry`='-3100191';
UPDATE `gossip_texts` SET `content_loc7`='He escuchado tus palabras, Espíritu del gran oso, y las entiendo. Ahora busco tu bendición para aprender por completo el camino de la Garra.' WHERE `entry`='-3100192';
UPDATE `gossip_texts` SET `content_loc7`='Me gustaría volar a la Aldea Rut\'theran.' WHERE `entry`='-3100193';
UPDATE `gossip_texts` SET `content_loc7`='¿Sabes dónde puedo encontrar Medio colgante de Agilidad acuática?' WHERE `entry`='-3100194';
UPDATE `gossip_texts` SET `content_loc7`='Cuéntame una historia, Skorn.' WHERE `entry`='-3100195';
UPDATE `gossip_texts` SET `content_loc7`='Puedes ser franco, Neeru...' WHERE `entry`='-3100196';
UPDATE `gossip_texts` SET `content_loc7`='[PH] ...' WHERE `entry`='-3100197';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, comparte tu sabiduría conmigo, Jefe de Guerra.' WHERE `entry`='-3100198';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué descubrimientos?' WHERE `entry`='-3100199';
UPDATE `gossip_texts` SET `content_loc7`='¿Usurpador?' WHERE `entry`='-3100200';
UPDATE `gossip_texts` SET `content_loc7`='Con el debido respeto Jefe de Guerra, - ¿por qué impedir que sean destruidos? ¿No reforzaría esto nuestra posición?' WHERE `entry`='-3100201';
UPDATE `gossip_texts` SET `content_loc7`='Yo… no lo pienso de ese modo, Jefe de Guerra.' WHERE `entry`='-3100202';
UPDATE `gossip_texts` SET `content_loc7`='¡Sólo vivo para servir, Jefe de Guerra! Mi vida está vacía y sin sentido sin tu guía.' WHERE `entry`='-3100203';
UPDATE `gossip_texts` SET `content_loc7`='¡Por supuesto, Jefe de Guerra!' WHERE `entry`='-3100204';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué sabe usted de eso?' WHERE `entry`='-3100205';
UPDATE `gossip_texts` SET `content_loc7`='Te escucho, Demitrian.' WHERE `entry`='-3100206';
UPDATE `gossip_texts` SET `content_loc7`='Sige, por favor.' WHERE `entry`='-3100207';
UPDATE `gossip_texts` SET `content_loc7`='¿Una batalla?' WHERE `entry`='-3100208';
UPDATE `gossip_texts` SET `content_loc7`='<Asiente con la cabeza>' WHERE `entry`='-3100209';
UPDATE `gossip_texts` SET `content_loc7`='¿Desprevenido? ¿Cómo?' WHERE `entry`='-3100210';
UPDATE `gossip_texts` SET `content_loc7`='Entonces, ¿qué hará ahora Ragnaros?' WHERE `entry`='-3100211';
UPDATE `gossip_texts` SET `content_loc7`='Busco información sobre Natalia' WHERE `entry`='-3100212';
UPDATE `gossip_texts` SET `content_loc7`='¡Eso suena peligroso!' WHERE `entry`='-3100213';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué hiciste?' WHERE `entry`='-3100214';
UPDATE `gossip_texts` SET `content_loc7`='¿Quién?' WHERE `entry`='-3100215';
UPDATE `gossip_texts` SET `content_loc7`='Las mujeres hacen eso. ¿Qué exigen?' WHERE `entry`='-3100216';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué quieres decir?' WHERE `entry`='-3100217';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué pasó después?' WHERE `entry`='-3100218';
UPDATE `gossip_texts` SET `content_loc7`='Si, por favor continua.' WHERE `entry`='-3100219';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué lenguaje?' WHERE `entry`='-3100220';
UPDATE `gossip_texts` SET `content_loc7`='¡¿La sacerdotisa te atacó?!' WHERE `entry`='-3100221';
UPDATE `gossip_texts` SET `content_loc7`='Debería preguntar al mono sobre esto' WHERE `entry`='-3100222';
UPDATE `gossip_texts` SET `content_loc7`='Entonces que…' WHERE `entry`='-3100223';
UPDATE `gossip_texts` SET `content_loc7`='Ysera' WHERE `entry`='-3100224';
UPDATE `gossip_texts` SET `content_loc7`='Neltharion' WHERE `entry`='-3100225';
UPDATE `gossip_texts` SET `content_loc7`='Nozdormu' WHERE `entry`='-3100226';
UPDATE `gossip_texts` SET `content_loc7`='Alexstrasza' WHERE `entry`='-3100227';
UPDATE `gossip_texts` SET `content_loc7`='Malygos' WHERE `entry`='-3100228';
UPDATE `gossip_texts` SET `content_loc7`='Por favor llévame a la guarida del maestro.' WHERE `entry`='-3100229';
UPDATE `gossip_texts` SET `content_loc7`='¿Para qué función sirves?' WHERE `entry`='-3100230';
UPDATE `gossip_texts` SET `content_loc7`='¿Cuáles son las Placas de Uldum?' WHERE `entry`='-3100231';
UPDATE `gossip_texts` SET `content_loc7`='¿Dónde están las Placas de Uldum?' WHERE `entry`='-3100232';
UPDATE `gossip_texts` SET `content_loc7`='¿Perdón? Hemos sido ¿\"reprogramados para visitas\"? ¿Qué significa eso?' WHERE `entry`='-3100233';
UPDATE `gossip_texts` SET `content_loc7`='Entonces, ¿qué hay dentro de Uldum?' WHERE `entry`='-3100234';
UPDATE `gossip_texts` SET `content_loc7`='Volveré cuando tenga las Placas de Uldum.' WHERE `entry`='-3100235';
UPDATE `gossip_texts` SET `content_loc7`='Examine el cadáver con detalle…' WHERE `entry`='-3100236';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué me puedes decir de este fragmento?' WHERE `entry`='-3100237';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, dime la frase…' WHERE `entry`='-3100238';
UPDATE `gossip_texts` SET `content_loc7`='Sé que es algo tonto, pero a un joven tutor que es algo tímido le gusta la Huella de tu Pezuña.' WHERE `entry`='-3100239';
UPDATE `gossip_texts` SET `content_loc7`='Habla conmigo' WHERE `entry`='-3100240';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué haces aquí?' WHERE `entry`='-3100241';
UPDATE `gossip_texts` SET `content_loc7`='Puedo ayudarte' WHERE `entry`='-3100242';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué pasa?' WHERE `entry`='-3100243';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué pasó luego?' WHERE `entry`='-3100244';
UPDATE `gossip_texts` SET `content_loc7`='Él no es fiable, me aseguraré de esto.' WHERE `entry`='-3100245';
UPDATE `gossip_texts` SET `content_loc7`='Quisiera que me hicieras un nuevo Alijo de Mau\'ari' WHERE `entry`='-3100246';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué crees que se traen entre manos?' WHERE `entry`='-3100247';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué quieres que haga qué?' WHERE `entry`='-3100248';
UPDATE `gossip_texts` SET `content_loc7`='Muy bien, Chromie.' WHERE `entry`='-3100249';
UPDATE `gossip_texts` SET `content_loc7`='Estoy list$go:a; para comenzar la Matanza de Stratholme.' WHERE `entry`='-3100250';
UPDATE `gossip_texts` SET `content_loc7`='Sí, mi príncipe. Estamos listos.' WHERE `entry`='-3100251';
UPDATE `gossip_texts` SET `content_loc7`='Sólo hacemos lo mejor para Lordaeron su Alteza.' WHERE `entry`='-3100252';
UPDATE `gossip_texts` SET `content_loc7`='Estoy list$go:a;' WHERE `entry`='-3100253';
UPDATE `gossip_texts` SET `content_loc7`='¡Por Lordaeron!' WHERE `entry`='-3100254';
UPDATE `gossip_texts` SET `content_loc7`='Estoy preparad$go:a; para luchar contra el Señor del Terror, señor.' WHERE `entry`='-3100255';
UPDATE `gossip_texts` SET `content_loc7`='¿Por qué he sido enviad$go:a; de vuelta a este lugar y momento?' WHERE `entry`='-3100256';
UPDATE `gossip_texts` SET `content_loc7`='¿Cuál fue esa decisión?' WHERE `entry`='-3100257';
UPDATE `gossip_texts` SET `content_loc7`='Así que ¿Cuál es el plan para interferir al Vuelo infinito?' WHERE `entry`='-3100258';
UPDATE `gossip_texts` SET `content_loc7`='[PH] Obtener Cronobengala' WHERE `entry`='-3100259';
UPDATE `gossip_texts` SET `content_loc7`='Mis compañeros y yo estamos con usted, Lady Valiente.' WHERE `entry`='-3100260';
UPDATE `gossip_texts` SET `content_loc7`='Estamos preparados para cualquier cosa que nos envié el Archimonde, Lady Valiente.' WHERE `entry`='-3100261';
UPDATE `gossip_texts` SET `content_loc7`='Estoy contigo, Thrall.' WHERE `entry`='-3100262';
UPDATE `gossip_texts` SET `content_loc7`='No tenemos nada que temer.' WHERE `entry`='-3100263';
UPDATE `gossip_texts` SET `content_loc7`='Así no podemos continuar. ¡Retirémonos!' WHERE `entry`='-3100264';
UPDATE `gossip_texts` SET `content_loc7`='Ayúdanos a defender Nordrassil' WHERE `entry`='-3100265';
UPDATE `gossip_texts` SET `content_loc7`='Enséñame recestas de cocina' WHERE `entry`='-3100266';
UPDATE `gossip_texts` SET `content_loc7`='Enséñame recetas de  alquimia' WHERE `entry`='-3100267';
UPDATE `gossip_texts` SET `content_loc7`='¡Se acabó! Estoy hart$go:a; de echarte una mano. ¡Es hora de que decidamos las cosas el campo de batalla!' WHERE `entry`='-3100268';
UPDATE `gossip_texts` SET `content_loc7`='[PH] Vuela la puerta, por favor' WHERE `entry`='-3100269';
UPDATE `gossip_texts` SET `content_loc7`='Sobrestante, estoy aquí para negociar en nombre de la Expedición Cenarion.' WHERE `entry`='-3100270';
UPDATE `gossip_texts` SET `content_loc7`='Sí... sí, soy yo.' WHERE `entry`='-3100271';
UPDATE `gossip_texts` SET `content_loc7`='Sí mayor. Dime más del libro.' WHERE `entry`='-3100272';
UPDATE `gossip_texts` SET `content_loc7`='Por favor, envíame a Skettis.' WHERE `entry`='-3100273';
UPDATE `gossip_texts` SET `content_loc7`='Llévame a Cresta Canto.' WHERE `entry`='-3100274';
UPDATE `gossip_texts` SET `content_loc7`='¡Estoy list$go:a; para mi vuelo de prueba!' WHERE `entry`='-3100275';
UPDATE `gossip_texts` SET `content_loc7`='Llévame a Foresta Ruuan.' WHERE `entry`='-3100276';
UPDATE `gossip_texts` SET `content_loc7`='Llévame a la Zona de Aterrizaje Razaan,' WHERE `entry`='-3100277';
UPDATE `gossip_texts` SET `content_loc7`='Sí, Arúspice. Puedes poseerme.' WHERE `entry`='-3100278';
UPDATE `gossip_texts` SET `content_loc7`='Envíame a la Plataforma Abisal' WHERE `entry`='-3100279';
UPDATE `gossip_texts` SET `content_loc7`='Envíame al Alto del Honor' WHERE `entry`='-3100280';
UPDATE `gossip_texts` SET `content_loc7`='¿Por qué no te escapas?' WHERE `entry`='-3100281';
UPDATE `gossip_texts` SET `content_loc7`='¡Tengo marcas para redimir!' WHERE `entry`='-3100282';
UPDATE `gossip_texts` SET `content_loc7`='He oído que tu perro Fei Fei cogió el rosario de Klatu…' WHERE `entry`='-3100283';
UPDATE `gossip_texts` SET `content_loc7`='<atrás>' WHERE `entry`='-3100284';
UPDATE `gossip_texts` SET `content_loc7`='Háblame de los Hijos de Lothar..' WHERE `entry`='-3100285';
UPDATE `gossip_texts` SET `content_loc7`='<más>' WHERE `entry`='-3100286';
UPDATE `gossip_texts` SET `content_loc7`='Háblame de tu patria.' WHERE `entry`='-3100287';
UPDATE `gossip_texts` SET `content_loc7`='Envíame a las Puertas Murketh y Shaadraz' WHERE `entry`='-3100288';
UPDATE `gossip_texts` SET `content_loc7`='Envíame al Puesto Devastación' WHERE `entry`='-3100289';
UPDATE `gossip_texts` SET `content_loc7`='Estoy en la misión de bombardeo del Comandante de vanguardia To\'arch ¡Necesito un destructor Dracoleón!' WHERE `entry`='-3100290';
UPDATE `gossip_texts` SET `content_loc7`='Envíame a la Plataforma Abisal' WHERE `entry`='-3100291';
UPDATE `gossip_texts` SET `content_loc7`='Déjame un jinete del viento, voy a la Avanzada Rompeloma.' WHERE `entry`='-3100292';
UPDATE `gossip_texts` SET `content_loc7`='Ogro, ¡necesito respuestas!' WHERE `entry`='-3100293';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué hacen los Puño de Roca tan lejos? Sabes que este es territorio Kurenai.' WHERE `entry`='-3100294';
UPDATE `gossip_texts` SET `content_loc7`='Y ¿crees que simplemente vas a comer lo que te dé la gana? Es evidentemente que intentas comerte los desechos de Telaar.' WHERE `entry`='-3100295';
UPDATE `gossip_texts` SET `content_loc7`='¡Esto significa la guerra, Zoquete! ¡He dicho guerra!' WHERE `entry`='-3100296';
UPDATE `gossip_texts` SET `content_loc7`='Veo hierros retorcidos y olor a tierra arrasada.' WHERE `entry`='-3100297';
UPDATE `gossip_texts` SET `content_loc7`='¿Bueno...?' WHERE `entry`='-3100298';
UPDATE `gossip_texts` SET `content_loc7`='[PH] Historia de los pupilos de Illidan' WHERE `entry`='-3100299';
UPDATE `gossip_texts` SET `content_loc7`='¿Legión?' WHERE `entry`='-3100300';
UPDATE `gossip_texts` SET `content_loc7`='¿Y ahora?' WHERE `entry`='-3100301';
UPDATE `gossip_texts` SET `content_loc7`='¿Cómo lo ves ahora?' WHERE `entry`='-3100302';
UPDATE `gossip_texts` SET `content_loc7`='¿Campamentos de Forja?' WHERE `entry`='-3100303';
UPDATE `gossip_texts` SET `content_loc7`='Ok.' WHERE `entry`='-3100304';
UPDATE `gossip_texts` SET `content_loc7`='[PH] Historia hecha' WHERE `entry`='-3100305';
UPDATE `gossip_texts` SET `content_loc7`='Hola, Abuela. Garrosh me ha dicho que quieres hablar conmigo.' WHERE `entry`='-3100306';
UPDATE `gossip_texts` SET `content_loc7`='Garrosh está más allá de redención, Abuela. Me temo que ayudando a los Mag\'har, me han convencido de que Garrosh es incapáz de guiar.' WHERE `entry`='-3100307';
UPDATE `gossip_texts` SET `content_loc7`='¿Tu incrementaste todos los orcos aquí, Abuela?' WHERE `entry`='-3100308';
UPDATE `gossip_texts` SET `content_loc7`='¿Tu que crees?' WHERE `entry`='-3100309';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué se puede hacer? Lo he intentado por todos los medios. He hecho todo lo posible para ayudar a la gente de Nagrand. Cada vez que me he acercado a Garrosh, me ha echado.' WHERE `entry`='-3100310';
UPDATE `gossip_texts` SET `content_loc7`='¿Dejar? ¿Cómo puedes decidir dejarlo?' WHERE `entry`='-3100311';
UPDATE `gossip_texts` SET `content_loc7`='¿Cuál es este deber?' WHERE `entry`='-3100312';
UPDATE `gossip_texts` SET `content_loc7`='¿Hay algo que pueda hacer por tí, Abuela?' WHERE `entry`='-3100313';
UPDATE `gossip_texts` SET `content_loc7`='Hice todo lo que pude, Abuela. Te doy las gracias por tus amables palabras.' WHERE `entry`='-3100314';
UPDATE `gossip_texts` SET `content_loc7`='Abuela, ¿eres la madre de Durotan?' WHERE `entry`='-3100315';
UPDATE `gossip_texts` SET `content_loc7`='Abuela, nunca he tenido el honor. Durotan murió mucho antes de mi tiempo, pero sus hazañas son conocidas por todos en mi mundo. Los orcos de Azeroth residen en un lugar conocido como Durotar, el nombre de su hijo. Y ... (Se toma un momento para respirar y pensar sobre lo que está a punto de decirle a la' WHERE `entry`='-3100316';
UPDATE `gossip_texts` SET `content_loc7`='Es mi Jefe de Guerra, Abuela. El líder de mi pueblo. Para mi mundo. Él... él es el hijo de Durotan. Él es tu nieto.' WHERE `entry`='-3100317';
UPDATE `gossip_texts` SET `content_loc7`='Volveré a Azeroth inmediatamente, Abuela.' WHERE `entry`='-3100318';
UPDATE `gossip_texts` SET `content_loc7`='He matado a muchos de tus ogros, Lantresor. No tengo miedo.' WHERE `entry`='-3100319';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué sé yo? Para mi pareces un orco.' WHERE `entry`='-3100320';
UPDATE `gossip_texts` SET `content_loc7`='¿Y la otra mitad?' WHERE `entry`='-3100321';
UPDATE `gossip_texts` SET `content_loc7`='He oído hablar de los de tu clase, pero nunca pensé ver el día en que me encontraría con un mestizo.' WHERE `entry`='-3100322';
UPDATE `gossip_texts` SET `content_loc7`='Mis disculpas. No fue mi intención ofender. Estoy aquí en nombre de mi pueblo.' WHERE `entry`='-3100323';
UPDATE `gossip_texts` SET `content_loc7`='Mi pueblo y yo te pedimos que retires tus ogros Puño de Roca y ceses todos los ataques en nuestros territorios. A cambio, también retrocederán nuestras fuerzas.' WHERE `entry`='-3100324';
UPDATE `gossip_texts` SET `content_loc7`='Lucharemos hasta el final, pues, Lantresor. No nos quedaremos de brazos cruzados mientras saqueas nuestros pueblos y matas a nuestra gente.' WHERE `entry`='-3100325';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué debo hacer?' WHERE `entry`='-3100326';
UPDATE `gossip_texts` SET `content_loc7`='Envíame a  Ultris' WHERE `entry`='-3100327';
UPDATE `gossip_texts` SET `content_loc7`='Ten la Talega de Flanis' WHERE `entry`='-3100328';
UPDATE `gossip_texts` SET `content_loc7`='Ten la Talega de Kagrosh' WHERE `entry`='-3100329';
UPDATE `gossip_texts` SET `content_loc7`='Estoy aquí por ti, sobrestante.' WHERE `entry`='-3100330';
UPDATE `gossip_texts` SET `content_loc7`='¡Cómo te atreves a cuestionar a  un sobrestanter de los Faucedraco!' WHERE `entry`='-3100331';
UPDATE `gossip_texts` SET `content_loc7`='¿Quién habla de mí? ¿De qué roto estás hablando?' WHERE `entry`='-3100332';
UPDATE `gossip_texts` SET `content_loc7`='Continúa por favor.' WHERE `entry`='-3100333';
UPDATE `gossip_texts` SET `content_loc7`='¿Quiénes son esos postores?' WHERE `entry`='-3100334';
UPDATE `gossip_texts` SET `content_loc7`='Bueno... sí.' WHERE `entry`='-3100335';
UPDATE `gossip_texts` SET `content_loc7`='Te estoy escuchando, dragón.' WHERE `entry`='-3100336';
UPDATE `gossip_texts` SET `content_loc7`='¡Pero sois dragones! ¿Cómo podrían hacer esto los orcos por vosotros?' WHERE `entry`='-3100337';
UPDATE `gossip_texts` SET `content_loc7`='¿Tu compañer$go:a;?' WHERE `entry`='-3100338';
UPDATE `gossip_texts` SET `content_loc7`='He batallado muchas bestias, dragón. Te ayudaré.' WHERE `entry`='-3100339';
UPDATE `gossip_texts` SET `content_loc7`='Estoy list$go:a; para escuchar tu historia, Oronok.' WHERE `entry`='-3100340';
UPDATE `gossip_texts` SET `content_loc7`='¿Cómo puedo encontrar la clave?' WHERE `entry`='-3100341';
UPDATE `gossip_texts` SET `content_loc7`='¿Cómo sabes todo esto?' WHERE `entry`='-3100342';
UPDATE `gossip_texts` SET `content_loc7`='Aún ¿qué? Oronok, ¿qué es?' WHERE `entry`='-3100343';
UPDATE `gossip_texts` SET `content_loc7`='Continúa, por favor.' WHERE `entry`='-3100344';
UPDATE `gossip_texts` SET `content_loc7`='Entonces, ¿qué hay ahora de la clave? ¿Y tus hijos?' WHERE `entry`='-3100345';
UPDATE `gossip_texts` SET `content_loc7`='Encontraré a tus hijos y la clave, Oronok.' WHERE `entry`='-3100346';
UPDATE `gossip_texts` SET `content_loc7`='¿Quiénes son los Sha\'tar?' WHERE `entry`='-3100347';
UPDATE `gossip_texts` SET `content_loc7`='¿No es Shattrath una ciudad draenei? ¿Por qué permitís otros aquí?' WHERE `entry`='-3100348';
UPDATE `gossip_texts` SET `content_loc7`='Solo he escuchado pronunciar tu nombre en voz baja, mago. ¿Quién eres tú?' WHERE `entry`='-3100349';
UPDATE `gossip_texts` SET `content_loc7`='Vamos, por favor.' WHERE `entry`='-3100350';
UPDATE `gossip_texts` SET `content_loc7`='Ya veo.' WHERE `entry`='-3100351';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué hiciste entonces?' WHERE `entry`='-3100352';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué pasó luego?' WHERE `entry`='-3100353';
UPDATE `gossip_texts` SET `content_loc7`='Aún había otra cosa que quería preguntarte.' WHERE `entry`='-3100354';
UPDATE `gossip_texts` SET `content_loc7`='Le debes dinero a Sim\'salabim. ¡Entréguemelo o muere!' WHERE `entry`='-3100355';
UPDATE `gossip_texts` SET `content_loc7`='Llévame a las Cavernas del Tiempo.' WHERE `entry`='-3100356';
UPDATE `gossip_texts` SET `content_loc7`='Le debes dinero a Sim\'salabim. ¡Entréguemelo o muere!' WHERE `entry`='-3100357';
UPDATE `gossip_texts` SET `content_loc7`='¡De nuevo... entrégame el dinero o muere!' WHERE `entry`='-3100358';
UPDATE `gossip_texts` SET `content_loc7`='Envíame a Ogri\'la por favor' WHERE `entry`='-3100359';
UPDATE `gossip_texts` SET `content_loc7`='Dame tu marca, sabio anciano.' WHERE `entry`='-3100360';
UPDATE `gossip_texts` SET `content_loc7`='Dame tu marca, poderoso anciano.' WHERE `entry`='-3100361';
UPDATE `gossip_texts` SET `content_loc7`='Le debes dinero a Sim\'salabim. ¡Entréguemelo o muere!' WHERE `entry`='-3100362';
UPDATE `gossip_texts` SET `content_loc7`='Ofrezco un trato' WHERE `entry`='-3100363';
UPDATE `gossip_texts` SET `content_loc7`='Soy un mensajero de los Draenei' WHERE `entry`='-3100364';
UPDATE `gossip_texts` SET `content_loc7`='Conseguir mensage' WHERE `entry`='-3100365';
UPDATE `gossip_texts` SET `content_loc7`='Especialista, ¿eh? ¿De todos modos? qué clase de especialista eres ' WHERE `entry`='-3100366';
UPDATE `gossip_texts` SET `content_loc7`='Déjame ver tus suministros de venenos y componentes.' WHERE `entry`='-3100367';
UPDATE `gossip_texts` SET `content_loc7`='Teletransportame al otro Juramorte Lengua de ceniza' WHERE `entry`='-3100368';
UPDATE `gossip_texts` SET `content_loc7`='Estamos dispuestos a hacer frente Illidan' WHERE `entry`='-3100369';
UPDATE `gossip_texts` SET `content_loc7`='Estamos dispuestos a luchar junto a ti, Akama' WHERE `entry`='-3100370';
UPDATE `gossip_texts` SET `content_loc7`='Quiero saber más.' WHERE `entry`='-3409000';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué más tiene que decir?' WHERE `entry`='-3409001';
UPDATE `gossip_texts` SET `content_loc7`='Nos desafió y hemos venido. ¿Dónde está este maestro del que habla?' WHERE `entry`='-3409002';
UPDATE `gossip_texts` SET `content_loc7`='No he cometido errores.' WHERE `entry`='-3469000';
UPDATE `gossip_texts` SET `content_loc7`='Ha perdido la cabeza, Nefarius. Hablas con enigmas.' WHERE `entry`='-3469001';
UPDATE `gossip_texts` SET `content_loc7`='Por favor.' WHERE `entry`='-3469002';
UPDATE `gossip_texts` SET `content_loc7`='¡No puedo, Vaelastrasz! ¡Seguramente se puede hacer algo para curarte!' WHERE `entry`='-3469003';
UPDATE `gossip_texts` SET `content_loc7`='¡¡¡Vaelastrasz, no!!!' WHERE `entry`='-3469004';
UPDATE `gossip_texts` SET `content_loc7`='Estoy dispuesto a ir al Castillo de Durnholde.' WHERE `entry`='-3560000';
UPDATE `gossip_texts` SET `content_loc7`='Necesito un pack de bombas incendiarias.' WHERE `entry`='-3560001';
UPDATE `gossip_texts` SET `content_loc7`='Taretha no puede verte, Thrall.' WHERE `entry`='-3560002';
UPDATE `gossip_texts` SET `content_loc7`='La situación es bastante complicada, Thrall. Sería lo mejor para ti que te dirigieses a las montañas ahora, antes de que más hombres de Lodonegro aparezcan. Nos aseguraremos de que Taretha esté a salvo.' WHERE `entry`='-3560003';
UPDATE `gossip_texts` SET `content_loc7`='Estamos listos, Thrall.' WHERE `entry`='-3560004';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué extraño mago?' WHERE `entry`='-3560005';
UPDATE `gossip_texts` SET `content_loc7`='Vamos a salir. Taretha. No te preocupes. Dudo que el mago deambule demasiado lejos.' WHERE `entry`='-3560006';
UPDATE `gossip_texts` SET `content_loc7`='¿Que crees que están haciendo?' WHERE `entry`='-3595000';
UPDATE `gossip_texts` SET `content_loc7`='¿Que quieres que haga qué?' WHERE `entry`='-3595001';
UPDATE `gossip_texts` SET `content_loc7`='Muy bien, Cromi.' WHERE `entry`='-3595002';
UPDATE `gossip_texts` SET `content_loc7`='¿Por qué me han devuelto a este lugar y en este preciso momento?' WHERE `entry`='-3595003';
UPDATE `gossip_texts` SET `content_loc7`='¿Cuál fue esa decisión?' WHERE `entry`='-3595004';
UPDATE `gossip_texts` SET `content_loc7`='Asi pues ¿cual es el plan para interferir el Vuelo infinito?' WHERE `entry`='-3595005';
UPDATE `gossip_texts` SET `content_loc7`='Teletransporte al Campamento Base de la Expedición.' WHERE `entry`='-3603000';
UPDATE `gossip_texts` SET `content_loc7`='Teletransporte al Campo de Formación.' WHERE `entry`='-3603001';
UPDATE `gossip_texts` SET `content_loc7`='Teletransporte a La Forja Colosal.' WHERE `entry`='-3603002';
UPDATE `gossip_texts` SET `content_loc7`='Teletransporte a La Chatarrería.' WHERE `entry`='-3603003';
UPDATE `gossip_texts` SET `content_loc7`='Teletransporte a la Antecámara de Ulduar.' WHERE `entry`='-3603004';
UPDATE `gossip_texts` SET `content_loc7`='Teletransporte a La Pasarela Devastada.' WHERE `entry`='-3603005';
UPDATE `gossip_texts` SET `content_loc7`='Teletransporte al Invernadero de Vida.' WHERE `entry`='-3603006';
UPDATE `gossip_texts` SET `content_loc7`='Teletransporte a La Chispa de la Imaginación.' WHERE `entry`='-3603007';
UPDATE `gossip_texts` SET `content_loc7`='Teletransporte a la Prisión de Yogg-Saron.' WHERE `entry`='-3603008';
UPDATE `gossip_texts` SET `content_loc7`='Activar los cristales cuando tengamos problemas, ¿verdad?' WHERE `entry`='-3608000';
UPDATE `gossip_texts` SET `content_loc7`='Proteje a tu pueblo, retendremos a las fuerzas del Vuelo Azul en la bahía.' WHERE `entry`='-3608001';
UPDATE `gossip_texts` SET `content_loc7`='Si. Estamos preparados para lo que se nos presente.' WHERE `entry`='-3649000';
UPDATE `gossip_texts` SET `content_loc7`='¡Saca el primer desafío!' WHERE `entry`='-3649001';
UPDATE `gossip_texts` SET `content_loc7`='¡Queremos otra oportunidad en aquellas bestias!' WHERE `entry`='-3649002';
UPDATE `gossip_texts` SET `content_loc7`='¿Qué nuevo desfío nos espera?' WHERE `entry`='-3649003';
UPDATE `gossip_texts` SET `content_loc7`='Estamos listos para luchar con el brujo de nuevo.' WHERE `entry`='-3649004';
UPDATE `gossip_texts` SET `content_loc7`='¡Por supuesto!' WHERE `entry`='-3649005';
UPDATE `gossip_texts` SET `content_loc7`='¡Dé la señal! ¡Estamos listos para partir!' WHERE `entry`='-3649006';
UPDATE `gossip_texts` SET `content_loc7`='Es complicado, ¿eh?' WHERE `entry`='-3649007';
UPDATE `gossip_texts` SET `content_loc7`='¿Val\'kyr? Listos, a por ellas' WHERE `entry`='-3649008';
UPDATE `gossip_texts` SET `content_loc7`='Aprecio tus elogios, Maestro del Coliseo.' WHERE `entry`='-3649009';
UPDATE `gossip_texts` SET `content_loc7`='Esto es extraño...' WHERE `entry`='-3649010';